apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: my-app-scaledobject
  labels:
    deploymentName: my-app
spec:
  scaleTargetRef:
    deploymentName: my-app
  triggers:
  - type: rabbitmq
    metadata:
      queueName: my-queue
      host: rabbitmq
      port: 5672
      username: guest
      password: guest
    policy:
      type: count
      value: "3"
